### ISSUE TITLE
I'm still searching somebody able to aswer what I already ask here

### ISSUE THREAD

**Issue by cryptid11** [MichaelXavier/kickass-torrents-dump-parser#1]
https://github.com/nicoboss/KickassCopy/issues/3

Sorry, not strictly related, but maybe lot more after kat shutdown!

**Comment by MichaelXavier** [comment]
I'm afraid I don't follow. What's the issue/question I can help with?

**Comment by cryptid11** [comment]
Easy, kickass torrents use to release last version of their torrent db every day, as I presume you know, and for now the last one I find is this https://web.archive.org/web/20150416071329/http://kickass.to/api - pretty old - did you know of a more recent release?

**Comment by MichaelXavier** [comment]
Sorry, I don't.
